version: '3'
services:
  kuma-control-plane:
    image: kong/kuma-cp:1.3.3
    environment:
    - KMESH_LICENSE_PATH=/license.json
    - KUMA_MODE=zone
    - KUMA_MULTIZONE_ZONE_NAME=universal-container-1
    - KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpcs://a3528c902347647a3867927ede5d4221-170331957.us-east-2.elb.amazonaws.com:5685
    - KUMA_DNS_SERVER_PORT=53
    - KUMA_GENERAL_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_DP_SERVER_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_API_SERVER_AUTH_CLIENT_CERTS_DIR=/
    - KUMA_GENERAL_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    - KUMA_DP_SERVER_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    working_dir: /
    command:
    - "run"
    - "--license-path=/license.json"
    volumes:
    - ./license.json:/license.json
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.key:/ip-172-31-30-10.us-east-2.compute.internal.key
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.crt:/ip-172-31-30-10.us-east-2.compute.internal.crt
    - /home/ec2-user/myCA.pem:/myCA.pem
    expose:
    - "5678"
    - "5680"
    - "5681"
    - "5682"
    - "53"
    ports:
    - "53:53"
    - "5678:5678"
    - "5680:5680"
    - "5681:5681"
    - "5682:5682"
    networks:
      kuma-example:
        ipv4_address: 172.24.0.2

  kuma-example-app-sidecar:
    image: kong/kuma-dp:1.3.3
    environment:
    - KUMA_GENERAL_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_DNS_SERVER_PORT=53
    - KUMA_DNS_SERVER_CIDR=240.0.0.0/4
    - KUMA_DP_SERVER_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_API_SERVER_AUTH_CLIENT_CERTS_DIR=/home/ec2-user
    - KUMA_DNS_SERVER_DOMAIN=mesh
    - KUMA_GENERAL_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    - KUMA_DP_SERVER_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    - KUMA_DATAPLANE_ADMIN_PORT=9901
    working_dir: /
    command:
    - "run"
    - "--cp-address=https://ip-172-31-30-10.us-east-2.compute.internal:5678/"
    - "--dataplane-token-file=/token"
    - "--ca-cert-file=/myCA.pem"
    - "--log-level=info"
    - "--dataplane-file=/dataplane.yaml"
    - "--dns-enabled"
    - "--dns-coredns-path=/kong-mesh-1.3.3/bin"
    - "--opa-enabled=false"
    volumes:
    - /home/ec2-user/token:/token
    - /home/ec2-user/dataplane.yaml:/dataplane.yaml
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.key:/ip-172-31-30-10.us-east-2.compute.internal.key
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.crt:/ip-172-31-30-10.us-east-2.compute.internal.crt
    - /home/ec2-user/myCA.pem:/myCA.pem
    depends_on:
    - kuma-example-app
    network_mode: "service:kuma-example-app"

  kuma-example-client-sidecar:
    image: kong/kuma-dp:1.3.3
    environment:
    - KUMA_GENERAL_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_DNS_SERVER_PORT=53
    - KUMA_DNS_SERVER_CIDR=240.0.0.0/4
    - KUMA_DP_SERVER_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_API_SERVER_AUTH_CLIENT_CERTS_DIR=/home/ec2-user
    - KUMA_DNS_SERVER_DOMAIN=mesh
    - KUMA_GENERAL_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    - KUMA_DP_SERVER_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    - KUMA_DATAPLANE_ADMIN_PORT=9901
    working_dir: /
    command:
    - "run"
    - "--cp-address=https://ip-172-31-30-10.us-east-2.compute.internal:5678/"
    - "--dataplane-token-file=/token"
    - "--ca-cert-file=/myCA.pem"
    - "--dataplane-file=/dataplane.yaml"
    - "--log-level=info"
    - "--dns-enabled"
    - "--dns-coredns-path=/kong-mesh-1.3.3/bin"
    - "--opa-enabled=false"
    volumes:
    - /home/ec2-user/token-client:/token
    - /home/ec2-user/dataplane-client-transparent.yaml:/dataplane.yaml
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.key:/ip-172-31-30-10.us-east-2.compute.internal.key
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.crt:/ip-172-31-30-10.us-east-2.compute.internal.crt
    - /home/ec2-user/myCA.pem:/myCA.pem
    network_mode: "service:kuma-example-client"

  kuma-example-app:
    image: kennethreitz/httpbin
    depends_on:
    - kuma-control-plane
    networks:
      kuma-example: 
        ipv4_address: 172.24.0.10
    expose:
    - "8080"
    - "10000"
    ports:
    - "8080:8080"
    - "10000:10000"

  kuma-example-client:
    image: bdecoste/tools:iptables-transparent
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    privileged: true
    command:
    - sh
    - -c
    - sleep infinity
    depends_on:
    - kuma-control-plane
    networks:
      kuma-example:
        ipv4_address: 172.24.0.11

  client-init:
    image: bdecoste/tools:iptables-transparent
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    command:
    - sh
    - -c
    - /kong-mesh-1.3.3/bin/kumactl install transparent-proxy --skip-resolv-conf --redirect-all-dns-traffic  --redirect-outbound-port 15001 --redirect-inbound=true --redirect-inbound-port 15006 --redirect-inbound-port-v6 15010 --kuma-dp-user kuma-dp
    network_mode: "service:kuma-example-client"
    depends_on:
      - kuma-example-client
      - kuma-example-client-sidecar

  kuma-example-installer:
    image: kong/kumactl:1.3.3
    networks:
      kuma-example: {}
    volumes:
    - ./kuma-example-installer.sh:/kuma-example/kuma-example-installer.sh
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.key:/ip-172-31-30-10.us-east-2.compute.internal.key
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.crt:/ip-172-31-30-10.us-east-2.compute.internal.crt
    - /home/ec2-user/myCA.pem:/myCA.pem
    command:
    - /kuma-example/kuma-example-installer.sh
    depends_on:
      - kuma-control-plane

  kumactl:
    image: kong/kumactl:1.3.3
    volumes:
    - ./policies:/kuma-example/policies
    command:
    - sh
    - -c
    - kumactl config control-planes add --name universal-3 --address http://ip-172-31-30-10.us-east-2.compute.internal:5681 --overwrite && sleep infinity
    networks:
      kuma-example: {}
    depends_on:
      - kuma-control-plane

  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      kuma-example:
        ipv4_address: 172.24.0.12

  migration:
    image: kong/kong-gateway:2.5.0.0-alpine
    command:
      - kong
      - migrations
      - bootstrap
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=ip-172-31-30-10.us-east-2.compute.internal"
      - "KONG_PG_PASSWORD=kong"
      - "KONG_PASSWORD=kong"
    depends_on:
      - postgres
    networks:
      kuma-example: {}

  gateway:
    image: kong/kong-gateway:2.5.0.0-alpine
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=ip-172-31-30-10.us-east-2.compute.internal"
      - "KONG_PG_PASSWORD=kong"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=localhost:8001"
      - "KONG_ADMIN_GUI_URL=http://172.24.0.13:8002"
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
      - '8002:8002'
      - '8445:8445'
      - '8003:8003'
      - '8004:8004'
    networks:
      kuma-example:
        ipv4_address: 172.24.0.13
    depends_on:
      migration:
        condition: service_completed_successfully

  gateway-sidecar:
    image: kong/kuma-dp:1.3.3
    environment:
    - KUMA_GENERAL_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_DNS_SERVER_PORT=53
    - KUMA_DNS_SERVER_CIDR=240.0.0.0/4
    - KUMA_DP_SERVER_TLS_KEY_FILE=/ip-172-31-30-10.us-east-2.compute.internal.key
    - KUMA_API_SERVER_AUTH_CLIENT_CERTS_DIR=/home/ec2-user
    - KUMA_DNS_SERVER_DOMAIN=mesh
    - KUMA_GENERAL_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    - KUMA_DP_SERVER_TLS_CERT_FILE=/ip-172-31-30-10.us-east-2.compute.internal.crt
    - KUMA_DATAPLANE_ADMIN_PORT=9901
    working_dir: /
    command:
    - "run"
    - "--cp-address=https://ip-172-31-30-10.us-east-2.compute.internal:5678/"
    - "--dataplane-token-file=/token"
    - "--ca-cert-file=/myCA.pem"
    - "--dataplane-file=/dataplane.yaml"
    - "--log-level=info"
    - "--dns-enabled"
    - "--dns-coredns-path=/kong-mesh-1.3.3/bin"
    - "--opa-enabled=false"
    - "--dns-coredns-config-template-path=/coredns.template"
    volumes:
    - /home/ec2-user/coredns.template:/coredns.template
    - /home/ec2-user/token-gateway:/token
    - /home/ec2-user/dataplane-gateway-transparent.yaml:/dataplane.yaml
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.key:/ip-172-31-30-10.us-east-2.compute.internal.key
    - /home/ec2-user/ip-172-31-30-10.us-east-2.compute.internal.crt:/ip-172-31-30-10.us-east-2.compute.internal.crt
    - /home/ec2-user/myCA.pem:/myCA.pem
    network_mode: "service:gateway"

  gateway-init:
    image: bdecoste/tools:iptables-transparent
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    command:
    - sh
    - -c
    - /kong-mesh-1.3.3/bin/kumactl install transparent-proxy --skip-resolv-conf --redirect-all-dns-traffic  --redirect-outbound-port 15001 --redirect-inbound=true --redirect-inbound-port 15006 --redirect-inbound-port-v6 15010 --kuma-dp-user kuma-dp
    network_mode: "service:gateway"
    depends_on:
      - gateway
      - gateway-sidecar

  gateway-debug:
    image: bdecoste/tools:iptables-transparent
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    command:
    - sh
    - -c
    - sleep infinity 
    network_mode: "service:gateway"
    depends_on:
      - gateway
      - gateway-sidecar

networks:
  kuma-example: 
    driver: bridge      
    ipam:
      config:
      - subnet: 172.24.0.0/16
        gateway: 172.24.0.1
